language:
  - node_js
  - ruby
node_js: "4"
rvm: "2.2"
os:
  - linux
  - osx
script: npm run dist
sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - icnsutils
      - graphicsmagick
      - ruby-dev
      - build-essential
      - g++-4.8
before_install:
  - gem install fpm
cache:
  - node_modules
  - app/node_modules