language: c
osx_image: xcode7.3
matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

script: npm run dist
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - clang-3.7
      - graphicsmagick
before_install:
  - gem install fpm
cache:
  - node_modules
  - app/node_modules
install:
- nvm install 6
- npm install npm -g
- npm install
- npm prune
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-linux-amd64-1.2.0.tar.gz | tar -xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git-lfs-1.2.0/git-lfs pull; fi
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: acASzVSEsuVdjny/Wq9tI45z3sBqzXbamQusNEjv2SVIXd+FcnqWO8FogDkiPl2ARb0Z4NlEt0YJrKm0Ur5z7nTo/bSvQgKym4+oiV8CR5OshPCqxiy/nelf1CcO0ei2f9l5UMzfVJMhYxc0MgWhyxpUaNQjsSvBQzNzKXQbeoEWIVG+G3ZMKES972ffNQKubHJuG+JtxLmJlQAuMNbM0KcEG0lsQhRu1Z/QqzlhzWaQUfqQvqpdzs29iFFTM3eja0Jdowu+9FqaP8XI6f5hyFxBPzF9XdpHblWEWp4OgEkqOmG3RS1x4/e0Pfh6cSOTpsU43HVVGHboQFRxmF6AsgJWqFZ2lJCnWmIHV3RtpwApbwGkIhBRdWT4HZHa287n4b9uybJ7aCXD2fkcD9Q52l5z9YpR4zPe4AnfWGudU7ZBdTAphm6bEs91bo0rKWeshHajR0P8JlHYCB5mMJ/QRLbstKvv1evLSoZtkbBga8HpY8JzjXnMxso0CKULFlUBFdoyCJ1PqLJFu/vQTR2caqAALNs075p4YDRbm+9NOEM5P4vNgs8lQjJrNpRzrjKvG3uWWZOjNL778JlI+xfW5r3q7hAyhHB13R2fFT3bc/Pn3A9X01NhrwUlCdKU+xluGNXjHmVAXqDKqUCPccqMiSegCS0C3PYPJSS+uX6G6Sg=
  file: ''
  on:
    branch: test
