language:
  - node_js
  - ruby
rvm: "2.2"
node_js: "6"
os:
  - linux
  - osx

script: if [[ "$TRAVIS_TAG" ]]; then npm run dist; npm run pack; fi
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - clang-3.7
      - graphicsmagick
      - ruby
cache:
  directories:
    - node_modules
    - app/node_modules
install:
  - npm install npm -g
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install fpm; fi
  - npm prune
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-linux-amd64-1.2.0.tar.gz | tar -xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git-lfs-1.2.0/git-lfs pull; fi
