language:
  - node_js
  - ruby
node_js: "4"
os:
  - linux
  - osx
script: npm run dist
sudo: required
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - ruby-dev
      - build-essential
before_install:
  - sudo gem install fpm
cache:
  - node_modules
  - app/node_modules