platform:
  - x64
install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune
build_script: npm run dist
test: off
deploy: off
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - 'app\node_modules'
environment:
  GH_TOKEN:
    secure: oXAtU/2izFnd/DW9h0Lt0iC2cvp+SLSjwZukkwsihL/bIktOV54XfxvDu05kbtIm