platform:
  - x64
install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune
build_script: npm run dist:win64
test: off
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - 'app\node_modules'